name: task_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.3
  http: ^1.2.1
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+4
  path_provider: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner: ^2.3.3
  http_mock_adapter: ^0.6.1
  sqflite_common_ffi: any
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
